### PR TITLE
Pre-commit hooks for python code in the project 

### PR DESCRIPTION
**Pull request by boonwj**
This adds git pre-commit hooks to python code in the project. It adds automatic code formatting ([black](https://github.com/python/black)) and code style checking ([flake8](https://gitlab.com/pycqa/flake8)) on every commit.

The hooks are setup using [pre-commit](https://pre-commit.com/).

### CODE REVIEW

**Comment by boonwj** [comment]
I am confused by what is a component (in pipeline/components directory) and what is a pipeline (pipeline directory) file. Is there a reason for their place in the directories?

**Comment by boonwj** [comment]
Oh another thing, I just found that the unit tests do not pass on my end. The 'result' directory was not created by the program. It passes when I create the directory on my own. 

FileNotFoundError: [Errno 2] No such file or directory: 'pipelines/components/lungSegment/result/sample_lungaw.nii.gz'

**Comment by UdomkarnBoonyaprasert** [comment]
- fileHandler.py is now removed. (changed to pathlib)
- test files still not moved to test folder (I'm not sure how to make the testing work when they're not in the same directory as pipelineController.py). This is temporary.
- setup.py renamed to setupDirectory.py
- showHU.py now uses pathlib
- setupDirectory.py should new check for result folder in lungSegment as well

note: content of the components folder (inside the pipelines folder) are modules that can not be executed on its own but are called from pipeline modules.

**Comment by boonwj** [comment]
Realised there are multiple usages of exit() that is meant for use in the interactive shell. Replace them with sys.exit() instead.

https://code-examples.net/en/q/633301
https://stackoverflow.com/questions/6501121/difference-between-exit-and-sys-exit-in-python

**Pull request merged**
